#!/usr/bin/env bash
# Push generated docs to pekkaklarck/manual and open a PR.
#
# Prerequisites:
#   - gh CLI installed and authenticated (gh auth login), OR
#     set GH_TOKEN / GITHUB_TOKEN in the environment with repo scope on pekkaklarck/manual
#   - Can be run from any directory; all paths are derived from the script location.
#
# Usage (from repo root):
#   bash doc/userguide-mkdocs/scripts/push_to_manual.sh [--skip-pipeline]
#
#   --skip-pipeline   Skip running pipeline.py; use already-generated docs as-is.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
MKDOCS_DIR="$REPO_ROOT/doc/userguide-mkdocs"
MANUAL_REPO="https://github.com/pekkaklarck/manual.git"
WORK_DIR="$(mktemp -d)"
MANUAL_DIR="$WORK_DIR/manual"
SKIP_PIPELINE=false

for arg in "$@"; do
  [[ "$arg" == "--skip-pipeline" ]] && SKIP_PIPELINE=true
done

cleanup() { rm -rf "$WORK_DIR"; }
trap cleanup EXIT

echo "==> Working directory: $WORK_DIR"

# --- Step 1: Run the pipeline ---
if [[ "$SKIP_PIPELINE" == false ]]; then
  echo "==> Running pipeline (--skip-fetch)..."
  cd "$MKDOCS_DIR/scripts"
  python pipeline.py --skip-fetch
  cd "$REPO_ROOT"
else
  echo "==> Skipping pipeline (--skip-pipeline flag set)"
fi

# --- Step 2: Clone pekkaklarck/manual ---
echo "==> Cloning pekkaklarck/manual..."
git clone --depth=1 "$MANUAL_REPO" "$MANUAL_DIR"

# --- Step 3: Run publish script ---
echo "==> Copying files..."
python "$SCRIPT_DIR/publish_to_manual.py" --manual-dir "$MANUAL_DIR"

# --- Step 4: Check for changes ---
cd "$MANUAL_DIR"
if git diff --quiet && git diff --cached --quiet; then
  echo "==> No changes to publish. The manual is already up to date."
  exit 0
fi

# --- Step 5: Create branch and commit ---
DATE="$(date +%Y-%m-%d)"
SHA="$(git -C "$REPO_ROOT" rev-parse --short HEAD)"
BRANCH="auto-update-${DATE}-${SHA}"

git checkout -b "$BRANCH"
git add -A
git commit -m "Auto-update from manykarim/robotframework@${SHA}

Generated by publish_to_manual.py. Sections updated:
  syntax      (from creating-test-data)
  execution   (from executing-tests)
  extend      (from extending)
  appendix    (from appendices)"

# --- Step 6: Push and open PR ---
echo "==> Pushing branch $BRANCH and opening PR..."
git push origin "$BRANCH"

gh pr create \
  --repo pekkaklarck/manual \
  --base main \
  --head "$BRANCH" \
  --title "Auto-update docs from robotframework@${SHA} (${DATE})" \
  --body "$(cat <<EOF
## Summary

Automated update from [manykarim/robotframework](https://github.com/manykarim/robotframework) commit \`${SHA}\`.

Generated by \`publish_to_manual.py\` using the conversion pipeline output.

### Sections updated
- \`syntax/\` ← \`creating-test-data/\`
- \`execution/\` ← \`executing-tests/\`
- \`extend/\` ← \`extending/\`
- \`appendix/\` ← \`appendices/\`

Please review for content correctness and nav changes before merging.
EOF
)"

echo "==> Done. PR opened against pekkaklarck/manual."
